---
title: "Random Forest Census tract"
author: "Mathew Attipetty"
date: "2022-11-02"
output: html_document
---

```{r knitr_init, echo=FALSE, cache=FALSE,include=FALSE}
Sys.setenv(LANGUAGE = "en")
library(knitr)
library(tidyverse)
library(caret)
## Global options
options(max.print="150") 
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=120)
```

```{r}
library(haven)
Census_pov <- read_dta("Censustract-cleaned-withregion.dta")
Census_pov
Census_pov <- subset(Census_pov, select = -c(v1, censustract, state, county, totalpop, men, women, citizen,income, incomepercaperr, childpoverty, service, office, construction, production, meancommute, employed))
Census_pov <- na.omit(Census_pov)



set.seed(53706)
trainIndex <- createDataPartition(Census_pov$poverty, p = .8, 
                                  list = FALSE, 
                                  times = 1)

train <- Census_pov[ trainIndex,]
test <- Census_pov[-trainIndex,]

```

#LASSO time 
```{r}

library(leaps)
regfit.fwd=regsubsets(poverty~.,train,nvmax = 256,method="forward") # default nvmax = 256 # RSS
reg.summary <- summary(regfit.fwd)
```

```{r}
reg.summary$rsq # R square
par(mfrow=c(2,2))
plot(reg.summary$rss,xlab="Number of Variables",ylab="RSS",type="l") # residual sum of square
plot(reg.summary$adjr2,xlab="Number of Variables",ylab="Adjusted RSq",type="l") # adjusted R square, adjust for the number of predictors
which.max(reg.summary$adjr2)
a <- which.max(reg.summary$adjr2)
points(a,reg.summary$adjr2[a], col="red",cex=2,pch=20) # cex--relative size, default = 1
plot(reg.summary$cp,xlab="Number of Variables",ylab="Cp",type='l') # 'l' type tells R to connect the point with the line.
which.min(reg.summary$cp)
b <- which.min(reg.summary$cp)
points(b,reg.summary$cp[b],col="red",cex=2,pch=20)
which.min(reg.summary$bic)
c <- which.min(reg.summary$bic)
plot(reg.summary$bic,xlab="Number of Variables",ylab="BIC",type='l')
points(c,reg.summary$bic[c],col="red",cex=2,pch=20)

bestset_fwd <- c(a,b,c)
```

```{r}
form <- {}
coefi <- {}

for (i in bestset_fwd) {
  coefi <- coef(regfit.fwd,i)
  form[i] <- "poverty ~"
  
  for (j in 1:i) {
    form[i] <- paste(form[i],names(coefi[j+1]))
    if (j < i){
      form[i] <- paste(form[i],'+')
    }
  }
}

```

```{r}
library(caret)
model <- list()

# Fit lm model using 10 x 5-fold CV: model
for (i in bestset_fwd) {
  model[[i]] <- train(
    formula(form[i]), 
    train,
    method = "lm",
    trControl = trainControl(
      method = "repeatedcv", 
      number = 10,  
      repeats = 5, 
      verboseIter = FALSE
    )
  )
}

# Print model to console

cv_rmse <- {}

for (i in bestset_fwd) {
  print(model[[i]]$results$RMSE)
  cv_rmse[i] <- model[[i]]$results$RMSE
}

(n <- which.min(cv_rmse))
form[which.min(cv_rmse)]
```

```{r}
final_model <- lm(formula(form[n]),train)
```

```{r}
test$pred <- predict(final_model,test)
sqrt(mean((test$pred - test$poverty)^2))
```

```{r}
float2poverty <- function(num){
  if (num < 0.5) {
    return(0)
    }
    else if (num > 0.5 & num < 8.5) {
    return(round(num))
    }
    else{
    return(9)
    }
}

pred_poverty <- {}
for (i in 1:nrow(test)) {
  pred_poverty[i] <- float2poverty(test$pred[i])
}
test$pred_poverty <- pred_poverty

table(test$poverty,test$pred_poverty)

nrow(test[test$poverty == test$pred_poverty,]) / nrow(test)
```

# **3. estimate ridge model using glmnet**

```{r}
test <- test %>% select(-pred,-pred_poverty)

train_notrue <- train %>% select(-poverty)
test_notrue <- test %>% select(-poverty)
library(glmnet)
ridge.mod <- glmnet(train_notrue,train$poverty,alpha=0,lambda=1)
coef(ridge.mod)

sqrt(sum(coef(ridge.mod)[-1]^2)) # term of model complexity
```

```{r}
test_pred <- predict(ridge.mod,as.matrix(test_notrue))
sqrt(mean((test_pred-test$poverty)^2))
```

# **4. estimate lasso model using glmnet**
```{r}
lasso.mod <- glmnet(train_notrue,train$poverty,alpha=1,lambda=0.1)
coef(lasso.mod)
sum(coef(lasso.mod) != 0)

sum(abs(coef(ridge.mod)[-1])) # term of model complexity
```

```{r}
test_pred <- predict(lasso.mod,as.matrix(test_notrue))
sqrt(mean((test_pred-test$poverty)^2))
```


```{r}
library(haven)
Census_pov <- read_dta("Censustract-cleaned-withregion.dta")
Census_pov
Census_pov <- subset(Census_pov, select = -c(v1, censustract, state, county))
Census_pov

Census_pov$poverty = as.factor(Census_pov$poverty)
Census_pov$midwest = as.factor(Census_pov$midwest)
Census_pov$south = as.factor(Census_pov$south)
Census_pov$northeast = as.factor(Census_pov$northeast)
Census_pov$west = as.factor(Census_pov$west)

set.seed(53706)
trainIndex <- createDataPartition(Census_pov$poverty, p = .8, 
                                  list = FALSE, 
                                  times = 1)

train <- Census_pov[ trainIndex,]
test <- Census_pov[-trainIndex,]
```

#lasso-ridge mix model

```{r}
lasso_ridge.mod <- glmnet(train_notrue,train$poverty,alpha=0.5,lambda=0.1)
0.5 * sum(abs(coef(lasso_ridge.mod)[-1])) + 0.5 * sqrt(sum(coef(lasso_ridge.mod)[-1]^2))# term of model complexity
coef(lasso_ridge.mod)
sum(coef(lasso_ridge.mod) != 0)

sum(abs(coef(lasso_ridge.mod)[-1]))
```

```{r}
test_pred <- predict(lasso_ridge.mod,as.matrix(test_notrue))
sqrt(mean((test_pred-test$poverty)^2))
```

```{r}
library(caret)
# From previous step
tuneGrid <- data.frame(
    alpha = c(0,0.2,0.5,0.8,1),
    lambda = c(seq(0.0001, 0.2, length = 100),seq(0.2, 2, length = 100))
)

# Fit random forest: model
lr_model <- train(
  poverty ~ .,
  data = train, 
  method = "glmnet",
  tuneGrid = tuneGrid,
  trControl = trainControl(
     method = "cv", 
     number = 10,  
     #repeats = 5, 
     verboseIter = FALSE
  )
)

# Print model to console
tuneGrid
lr_model
plot(lr_model)
```


```{r}
lr_model$bestTune
```

```{r}
pred <- predict(lr_model, newdata = test)
final <- as.data.frame(cbind(pred,test$poverty))
names(final) <- c("pred","true_poverty")
```

```{r}
sqrt(sum((final$pred-final$true_poverty)^2)/nrow(final))
```

```{r}
pred_poverty <- {}
for (i in 1:nrow(final)) {
  pred_poverty[i] <- float2poverty(final$pred[i])
}
final$pred_poverty <- pred_poverty

table(final$true_poverty,final$pred_poverty)

nrow(final[final$true_poverty == final$pred_poverty,]) / nrow(final)
```










